name: 'jQA DMN Plugin CI Build'

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: ./mvnw -B -P IT -Djqassistant.skip=false clean install
      - name: Deploy
        run: ./mvnw -B -DskipTests -Djqassistant.skip deploy -s .mvn/settings.xml -P github
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
