name: 'jQA DMN Plugin CI Build'

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 1.8.0, 9, 11 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Build only
        run: ./mvnw -DskipTests -Djqassistant.skip clean install
      - name: Unit Testing
        run: ./mvnw -Djqassistant.skip clean install
      - name: Integration Testing
        run: ./mvnw -Djqassistant.skip -P IT clean install
      - name: Full Build
        run: ./mvnw -P IT -Djqassistant.skip=false clean install
